DROP DATABASE IF EXISTS STARTREK;

CREATE DATABASE STARTREK;

USE STARTREK;

CREATE TABLE ACTORES(
  CODIGO INTEGER PRIMARY KEY,
  NOMBRE VARCHAR(50) NOT NULL,
  FECHA DATETIME NOT NULL,
  NACIONALIDAD VARCHAR(20) DEFAULT 'EEUU'
);

CREATE TABLE PERSONAJES(
  CODIGO INTEGER PRIMARY KEY,
  NOMBRE VARCHAR(50) NOT NULL,
  RAZA VARCHAR(20) NOT NULL,
  GRADO VARCHAR(20) NOT NULL,
  CODIGOACTOR INTEGER NOT NULL,
  CODIGOSUPERIOR INTEGER,
  
  FOREIGN KEY (CODIGOACTOR) REFERENCES ACTORES(CODIGO),
  FOREIGN KEY (CODIGOSUPERIOR) REFERENCES PERSONAJES(CODIGO)
);


CREATE TABLE PLANETAS(
  CODIGO INTEGER PRIMARY KEY,
  GALAXIA VARCHAR(50),
  NOMBRE VARCHAR(50) NOT NULL
);

CREATE TABLE CAPITULOS(
  TEMPORADA INTEGER,
  ORDEN VARCHAR(5),
/*  PRIMARY KEY (TEMPORADA,ORDEN)*/  /*NO SE PUEDE DEFINIR AQUI*/
  TITULO VARCHAR(50) NOT NULL,
  FECHA DATE NOT NULL,
  PRIMARY KEY (TEMPORADA,ORDEN) /*SE DEFINE AQUI O EN EL PROPIO CAMPO, PERO SI LA CLAVE ESTA FORMADA
   POR MAS DE UN CAMPO TIENE QUE IR AL FINAL DE LA DEFINICION DE TODOS LOS CAMPOS DE LA TABLA*/
);

CREATE TABLE PELICULAS(
  CODIGO INTEGER PRIMARY KEY,
  TITULO VARCHAR(50) NOT NULL,
  DIRECTOR VARCHAR(30) NOT NULL,
  ANIO DATE /*TIPO DATE ES SUFICIENTE PARA LA FECHA*/
);

CREATE TABLE PERSONAJESCAPITULOS (
  CODIGOPERSONAJE INTEGER PRIMARY KEY,
  TEMPORADA INTEGER NOT NULL,
  ORDEN VARCHAR(5) NOT NULL ,

  FOREIGN KEY (CODIGOPERSONAJE) REFERENCES PERSONAJES(CODIGO) ,
  FOREIGN KEY (TEMPORADA,ORDEN) REFERENCES CAPITULOS(TEMPORADA,ORDEN) /*REFERENCIA A LA CLAVE COMPLETA*/
 );

CREATE TABLE PERSONAJESPELICULAS(
  CODIGOPERSONAJE INTEGER,
  CODIGOPELICULA INTEGER,
  PRIMARY KEY(CODIGOPERSONAJE, CODIGOPELICULA),

  FOREIGN KEY (CODIGOPERSONAJE) REFERENCES PERSONAJES(CODIGO),/*REFERENCIA A LA TABLA PERSONAJES */
  FOREIGN KEY (CODIGOPELICULA) REFERENCES PELICULAS(CODIGO)
);

CREATE TABLE NAVES(
  CODIGO INTEGER PRIMARY KEY,
  NTRIPULANTES INTEGER,
  NOMBRE VARCHAR(50) NOT NULL
);

CREATE TABLE VISITAS (  
  CODIGONAVE INT,
  CODIGOPLANETA INT,
  TEMPORADA INTEGER NOT NULL,
  ORDEN VARCHAR(5) NOT NULL,  /*tipos iguales*/
  
  PRIMARY KEY (CODIGONAVE,CODIGOPLANETA,TEMPORADA,ORDEN),
  

  FOREIGN KEY (CODIGONAVE) REFERENCES NAVES(CODIGO),
  FOREIGN KEY (CODIGOPLANETA) REFERENCES PLANETAS(CODIGO),
  FOREIGN KEY (TEMPORADA,ORDEN) REFERENCES CAPITULOS(TEMPORADA,ORDEN)
 );